# Análise Comparativa de Embarcações (2021 vs 2024)

O objetivo desta análise é **comparar a quantidade de embarcações por tipo** entre os anos de **2021 e 2024**, para identificar mudanças no perfil da marina ao longo do tempo.

Com isso, será possível:
- Ver quais tipos de embarcação **aumentaram** ou **diminuíram**
- Medir a **diferença total** e a **variação percentual** por categoria
- Destacar tendências gerais de crescimento, queda ou estabilidade no período

In [1]:
# Passo a Passo do projeto

# Passo 1: Abrir a base de dados (Importar a base de dados)
import pandas as pd

table_2021 = pd.read_excel("../data/total_tipo_emb_2021.xlsx")
table_2024 = pd.read_excel("../data/total_tipo_emb_2024.xlsx")

# Passo 2: Visualizar a base de dados
    # entender as informações disponiveis
    # possiveis problemas/erro na base de dados
display(table_2021)
display(table_2024)

,DISTR_NAVAL,ORGAO,SG_ORGAO,UF_ORGAO,TIPO_EMBARCACAO,QUANTIDADE
0,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Balsa,11
1,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Barcaça,4
2,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Bote,2116
3,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Canoa,319
4,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Chata,4
...,...,...,...,...,...,...
1896,9º,Capitania Fluvial de Tabatinga,CFT,AM,Passageiro,18
1897,9º,Capitania Fluvial de Tabatinga,CFT,AM,Passageiro / Carga Geral,18
1898,9º,Capitania Fluvial de Tabatinga,CFT,AM,Pesqueiro,26
1899,9º,Capitania Fluvial de Tabatinga,CFT,AM,Rebocador,61
1900,9º,Capitania Fluvial de Tabatinga,CFT,AM,Tanque (transporte de granéis líquidos),1

,DISTR_NAVAL,ORGAO,SG_ORGAO,UF_ORGAO,TIPO_EMBARCACAO,QUANTIDADE
0,(null),Diretoria de Portos e Costas,DPC,RJ,Rebocador,2
1,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Balsa,11
2,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Barcaça,4
3,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Bote,2103
4,1º,Agência da Capitania dos Portos em Paraty,AGPRTI,RJ,Canoa,319
...,...,...,...,...,...,...
1899,9º,Capitania Fluvial de Tabatinga,CFT,AM,Passageiro,18
1900,9º,Capitania Fluvial de Tabatinga,CFT,AM,Passageiro / Carga Geral,18
1901,9º,Capitania Fluvial de Tabatinga,CFT,AM,Pesqueiro,26
1902,9º,Capitania Fluvial de Tabatinga,CFT,AM,Rebocador,61
1903,9º,Capitania Fluvial de Tabatinga,CFT,AM,Tanque (transporte de granéis líquidos),1

In [2]:
# Passo 3: Corrigir os problemas da base de dados (tratamento de dados)

# valores em formatos errados
    # nenhum

# informações vazias
table_2021 = table_2021.dropna()
table_2024 = table_2024.dropna()

display(table_2021.info())
display(table_2024.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1901 entries, 0 to 1900
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DISTR_NAVAL      1901 non-null   object
 1   ORGAO            1901 non-null   object
 2   SG_ORGAO         1901 non-null   object
 3   UF_ORGAO         1901 non-null   object
 4   TIPO_EMBARCACAO  1901 non-null   object
 5   QUANTIDADE       1901 non-null   int64
dtypes: int64(1), object(5)
memory usage: 89.2+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1904 entries, 0 to 1903
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DISTR_NAVAL      1904 non-null   object
 1   ORGAO            1904 non-null   object
 2   SG_ORGAO         1904 non-null   object
 3   UF_ORGAO         1904 non-null   object
 4   TIPO_EMBARCACAO  1904 non-null   object
 5   QUANTIDADE       1904 non-null   int64
dtypes: int64(1), object(5)
memory usage: 89.4+ KB

None

In [3]:
# Passo 4: Analise Inicial (Entender cada categoria e as quantidades)

# quantidade - contar quantidade total de embarcações por tipo
res_2021 = (table_2021
            .groupby("TIPO_EMBARCACAO", as_index=False)["QUANTIDADE"]
            .sum()
            .sort_values("QUANTIDADE", ascending=False)
            )

res_2024 = (table_2024
            .groupby("TIPO_EMBARCACAO", as_index=False)["QUANTIDADE"]
            .sum()
            .sort_values("QUANTIDADE", ascending=False)
            )
# verificar somente as 10 primeiras
display(res_2021.head(10))
display(res_2024.head(10))

             TIPO_EMBARCACAO  QUANTIDADE
8                       Bote      289620
32                    Lancha      232571
41                    Outros      137328
37     Moto-Aquática/similar      118383
11                     Canoa       52089
45                 Pesqueiro       29731
14                     Chata       22515
67                   Veleiro       17444
30                   Jangada       14068
43  Passageiro / Carga Geral       11660

             TIPO_EMBARCACAO  QUANTIDADE
8                       Bote      289706
31                    Lancha      232730
40                    Outros      137119
36     Moto-Aquática/similar      118391
11                     Canoa       51981
44                 Pesqueiro       29801
13                     Chata       22471
66                   Veleiro       17453
29                   Jangada       14049
42  Passageiro / Carga Geral       11662

In [4]:
# Passo 4: Tema visual e utilitarios de grafico

import plotly.express as px
import plotly.graph_objects as go

PALETA = ["#0B3C5D", "#328CC1", "#D9B310", "#1D2731", "#B1D4E0"]

def aplicar_tema(fig, titulo, x_titulo="", y_titulo=""):
    fig.update_layout(
        title=dict(text=titulo, x=0.02, xanchor="left", font=dict(size=20)),
        template="plotly_white",
        colorway=PALETA,
        font=dict(family="Segoe UI", size=13, color="#1f2937"),
        xaxis_title=x_titulo,
        yaxis_title=y_titulo,
        plot_bgcolor="white",
        paper_bgcolor="white",
        margin=dict(l=40, r=20, t=70, b=40),
        legend_title_text=""
    )
    fig.update_xaxes(showgrid=False, zeroline=False)
    fig.update_yaxes(showgrid=True, gridcolor="#e5e7eb", zeroline=False)
    return fig

# Ranking Top 10 - 2021
top_2021 = res_2021.head(10).sort_values("QUANTIDADE")
fig = px.bar(
    top_2021,
    x="QUANTIDADE",
    y="TIPO_EMBARCACAO",
    orientation="h",
    text="QUANTIDADE",
    color="QUANTIDADE",
    color_continuous_scale=["#B1D4E0", "#0B3C5D"]
)
fig = aplicar_tema(fig, "Top 10 tipos de embarcacao - 2021", "Quantidade", "Tipo de embarcacao")
fig.update_traces(textposition="outside", hovertemplate="%{y}<br>Quantidade: %{x:,}<extra></extra>")
fig.show()

# Ranking Top 10 - 2024
top_2024 = res_2024.head(10).sort_values("QUANTIDADE")
fig = px.bar(
    top_2024,
    x="QUANTIDADE",
    y="TIPO_EMBARCACAO",
    orientation="h",
    text="QUANTIDADE",
    color="QUANTIDADE",
    color_continuous_scale=["#B1D4E0", "#0B3C5D"]
)
fig = aplicar_tema(fig, "Top 10 tipos de embarcacao - 2024", "Quantidade", "Tipo de embarcacao")
fig.update_traces(textposition="outside", hovertemplate="%{y}<br>Quantidade: %{x:,}<extra></extra>")
fig.show()

In [5]:
# Passo 4

# Ajustar escrita diferente entre os anos
table_2021["TIPO_EMBARCACAO"] = table_2021["TIPO_EMBARCACAO"].astype(str).str.strip()
table_2024["TIPO_EMBARCACAO"] = table_2024["TIPO_EMBARCACAO"].astype(str).str.strip()


# Quantos tipos existem em cada ano
display("Tipos em 2021:", table_2021["TIPO_EMBARCACAO"].nunique())
display("Tipos em 2024:", table_2024["TIPO_EMBARCACAO"].nunique())

# Quais tipos são (lista)
tipos_2021 = sorted(table_2021["TIPO_EMBARCACAO"].unique())
tipos_2024 = sorted(table_2024["TIPO_EMBARCACAO"].unique())

display("Lista 2021:")
display(tipos_2021)

display("\nLista 2024:")
display(tipos_2024)

# O que tem em um ano e não teve no outro
so_2021 = sorted(set(tipos_2021) - set(tipos_2024))
so_2024 = sorted(set(tipos_2024) - set(tipos_2021))

display("Só em 2021:", so_2021)
display("Só em 2024:", so_2024)

'Tipos em 2021:'

68

'Tipos em 2024:'

67

'Lista 2021:'

['Alvarenga',
 'Anfíbia',
 'Apoio a Mergulho',
 'Apoio a ROV',
 'Apoio à Manobra',
 'Balsa',
 'Barcaça',
 'Batelão',
 'Bote',
 'Caiaque',
 'Caique',
 'Canoa',
 'Carga Geral',
 'Carga de Alta Velocidade (HSC Carga)',
 'Chata',
 'Cisterna (FSU)',
 'Curral',
 'Cábrea',
 'Dique Flutuante',
 'Draga',
 'Empurrador',
 'Escuna',
 'Estimulador de Poço',
 'Floating, Production, Storage and Off-Loading Unit (FPSO)',
 'Flotel',
 'Flutuante',
 'Graneleiro',
 'Hidroavião',
 'Hovercraft',
 'Iate',
 'Jangada',
 'Jet Boat',
 'Lancha',
 'Lançador de Linhas',
 'Laser',
 'Manuseio de Linhas',
 'Manuseio de Âncora (AHTS)',
 'Moto-Aquática/similar',
 'Multicasco (Catamarã, Trimarã, Tetramarã, etc)',
 'Multipurpose',
 'Oceonagráfico',
 'Outros',
 'Passageiro',
 'Passageiro / Carga Geral',
 'Passageiro de Alta Velocidade (HSC Passageiro)',
 'Pesqueiro',
 'Pesquisa',
 'Petroleiro',
 'Petroleiro e Químico',
 'Plataforma Auto-Elevável',
 'Plataforma Fixa',
 'Plataforma Semi-Submersível',
 'Porta-Contentor',
 'Quebra-gelo',
 'Químico',
 'Químico e Gaseiro',
 'Rebocador',
 'Roll-on / Roll-off Carga',
 'Roll-on / Roll-off Passageiro (Ferry Boat)',
 'Saveiro',
 'Sonda',
 'Supridor (Supply)',
 'Tanque (transporte de granéis líquidos)',
 'Traineira',
 'Transporte Escolar',
 'Transporte de Carga Pesada (Navio de Cargas Especiais)',
 'Transporte de Gases Liquefeitos',
 'Veleiro']

'\nLista 2024:'

['Alvarenga',
 'Anfíbia',
 'Apoio a Mergulho',
 'Apoio a ROV',
 'Apoio à Manobra',
 'Balsa',
 'Barcaça',
 'Batelão',
 'Bote',
 'Caiaque',
 'Caique',
 'Canoa',
 'Carga Geral',
 'Chata',
 'Cisterna (FSU)',
 'Curral',
 'Cábrea',
 'Dique Flutuante',
 'Draga',
 'Empurrador',
 'Escuna',
 'Estimulador de Poço',
 'Floating, Production, Storage and Off-Loading Unit (FPSO)',
 'Flotel',
 'Flutuante',
 'Graneleiro',
 'Hidroavião',
 'Hovercraft',
 'Iate',
 'Jangada',
 'Jet Boat',
 'Lancha',
 'Lançador de Linhas',
 'Laser',
 'Manuseio de Linhas',
 'Manuseio de Âncora (AHTS)',
 'Moto-Aquática/similar',
 'Multicasco (Catamarã, Trimarã, Tetramarã, etc)',
 'Multipurpose',
 'Oceonagráfico',
 'Outros',
 'Passageiro',
 'Passageiro / Carga Geral',
 'Passageiro de Alta Velocidade (HSC Passageiro)',
 'Pesqueiro',
 'Pesquisa',
 'Petroleiro',
 'Petroleiro e Químico',
 'Plataforma Auto-Elevável',
 'Plataforma Fixa',
 'Plataforma Semi-Submersível',
 'Porta-Contentor',
 'Quebra-gelo',
 'Químico',
 'Químico e Gaseiro',
 'Rebocador',
 'Roll-on / Roll-off Carga',
 'Roll-on / Roll-off Passageiro (Ferry Boat)',
 'Saveiro',
 'Sonda',
 'Supridor (Supply)',
 'Tanque (transporte de granéis líquidos)',
 'Traineira',
 'Transporte Escolar',
 'Transporte de Carga Pesada (Navio de Cargas Especiais)',
 'Transporte de Gases Liquefeitos',
 'Veleiro']

'Só em 2021:'

['Carga de Alta Velocidade (HSC Carga)']

'Só em 2024:'

[]

In [6]:
# Passo 5: Analise Detalhada ( Principais diferenças)
import pandas as pd

# (opcional, mas ajuda) padronizar textos
table_2021["TIPO_EMBARCACAO"] = table_2021["TIPO_EMBARCACAO"].astype(str).str.strip()
table_2024["TIPO_EMBARCACAO"] = table_2024["TIPO_EMBARCACAO"].astype(str).str.strip()

# garantir quantidade numérica
table_2021["QUANTIDADE"] = pd.to_numeric(table_2021["QUANTIDADE"], errors="coerce").fillna(0)
table_2024["QUANTIDADE"] = pd.to_numeric(table_2024["QUANTIDADE"], errors="coerce").fillna(0)

# 1) Agrupar por tipo (uma tabela por ano)
qtd_2021 = table_2021.groupby("TIPO_EMBARCACAO", as_index=False)["QUANTIDADE"].sum()
qtd_2024 = table_2024.groupby("TIPO_EMBARCACAO", as_index=False)["QUANTIDADE"].sum()

# 2) Renomear colunas pra não confundir no merge
qtd_2021 = qtd_2021.rename(columns={"QUANTIDADE": "QTD_2021"})
qtd_2024 = qtd_2024.rename(columns={"QUANTIDADE": "QTD_2024"})

# 3) Merge (outer = pega todos os tipos dos dois anos)
comparacao = pd.merge(qtd_2021, qtd_2024, on="TIPO_EMBARCACAO", how="outer")

# 4) Tudo que não existir em um ano vira 0
comparacao[["QTD_2021", "QTD_2024"]] = comparacao[["QTD_2021", "QTD_2024"]].fillna(0).astype(int)

# conferir
display(comparacao.sort_values("QTD_2024", ascending=False).head(20))

                                   TIPO_EMBARCACAO  QTD_2021  QTD_2024
8                                             Bote    289620    289706
32                                          Lancha    232571    232730
41                                          Outros    137328    137119
37                           Moto-Aquática/similar    118383    118391
11                                           Canoa     52089     51981
45                                       Pesqueiro     29731     29801
14                                           Chata     22515     22471
67                                         Veleiro     17444     17453
30                                         Jangada     14068     14049
43                        Passageiro / Carga Geral     11660     11662
12                                     Carga Geral     10776     10779
5                                            Balsa      7027      7019
59                                         Saveiro      6881      6879
19                                           Draga      6626      6627
42                                      Passageiro      6284      6322
25                                       Flutuante      5016      5022
6                                          Barcaça      4604      4585
56                                       Rebocador      3988      3981
63                                       Traineira      2457      2466
38  Multicasco (Catamarã, Trimarã, Tetramarã, etc)      1822      1840

In [7]:
# Passo 5: Calcular a diferença e a variação

# Diferença absoluta
comparacao["DIF"] = comparacao["QTD_2024"] - comparacao["QTD_2021"]

# Variação percentual (evita divisão por zero)
comparacao["VAR_%"] = ((comparacao["DIF"] / comparacao["QTD_2021"].replace(0, pd.NA)) * 100).round(2)

# Quando 2021 = 0, a variação % não faz sentido -> coloca como 0 (ou pode deixar como NA)
comparacao["VAR_%"] = comparacao["VAR_%"].fillna(0)

# Status
comparacao["STATUS"] = comparacao["DIF"].apply(
    lambda x: "Aumentou" if x > 0 else ("Diminuiu" if x < 0 else "Estável")
)

# Ver as maiores mudanças
display(comparacao.sort_values("DIF", ascending=False).head(10))  # top aumentos
display(comparacao.sort_values("DIF").head(10))                  # top quedas

,TIPO_EMBARCACAO,QTD_2021,QTD_2024,DIF,VAR_%,STATUS
32,Lancha,232571,232730,159,0.07,Aumentou
8,Bote,289620,289706,86,0.03,Aumentou
45,Pesqueiro,29731,29801,70,0.24,Aumentou
42,Passageiro,6284,6322,38,0.60,Aumentou
38,"Multicasco (Catamarã, Trimarã, Tetramarã, etc)",1822,1840,18,0.99,Aumentou
20,Empurrador,1567,1581,14,0.89,Aumentou
2,Apoio a Mergulho,82,96,14,17.07,Aumentou
67,Veleiro,17444,17453,9,0.05,Aumentou
63,Traineira,2457,2466,9,0.37,Aumentou
37,Moto-Aquática/similar,118383,118391,8,0.01,Aumentou

              TIPO_EMBARCACAO  QTD_2021  QTD_2024  DIF  VAR_%    STATUS
41                     Outros    137328    137119 -209  -0.15  Diminuiu
11                      Canoa     52089     51981 -108  -0.21  Diminuiu
14                      Chata     22515     22471  -44  -0.20  Diminuiu
6                     Barcaça      4604      4585  -19  -0.41  Diminuiu
30                    Jangada     14068     14049  -19  -0.14  Diminuiu
5                       Balsa      7027      7019   -8  -0.11  Diminuiu
56                  Rebocador      3988      3981   -7  -0.18  Diminuiu
10                     Caique       703       700   -3  -0.43  Diminuiu
33         Lançador de Linhas        73        70   -3  -4.11  Diminuiu
36  Manuseio de Âncora (AHTS)        97        94   -3  -3.09  Diminuiu

In [8]:
# Parte 5: Novos ou Sumiram em 2024
novos_2024 = comparacao[(comparacao["QTD_2021"] == 0) & (comparacao["QTD_2024"] > 0)]
sumiram_2024 = comparacao[(comparacao["QTD_2021"] > 0) & (comparacao["QTD_2024"] == 0)]

display(novos_2024.sort_values("QTD_2024", ascending=False))
display(sumiram_2024.sort_values("QTD_2021", ascending=False))

Empty DataFrame
Columns: [TIPO_EMBARCACAO, QTD_2021, QTD_2024, DIF, VAR_%, STATUS]
Index: []

,TIPO_EMBARCACAO,QTD_2021,QTD_2024,DIF,VAR_%,STATUS
13,Carga de Alta Velocidade (HSC Carga),1,0,-1,-100.0,Diminuiu

In [9]:
# Passo 5: Graficos de maiores altas e maiores quedas

# Top 10 aumentos
top_up = comparacao.sort_values("DIF", ascending=False).head(10).sort_values("DIF")

fig = px.bar(
    top_up,
    x="DIF",
    y="TIPO_EMBARCACAO",
    orientation="h",
    title="Top 10 aumentos (2024 - 2021)",
    text="DIF",
    color_discrete_sequence=["#16A34A"]
)
fig = aplicar_tema(fig, "Top 10 aumentos (2024 - 2021)", "Diferenca (QTD_2024 - QTD_2021)", "Tipo de embarcacao")
fig.add_vline(x=0, line_width=1, line_dash="dash", line_color="#6b7280")
fig.update_traces(textposition="outside", hovertemplate="%{y}<br>Diferenca: %{x:,}<extra></extra>")

fig.write_html("../data/comparativo_aumento_2021_2024.html")
fig.show()

# Top 10 quedas
top_down = comparacao.sort_values("DIF").head(10).sort_values("DIF")

fig = px.bar(
    top_down,
    x="DIF",
    y="TIPO_EMBARCACAO",
    orientation="h",
    title="Top 10 quedas (2024 - 2021)",
    text="DIF",
    color_discrete_sequence=["#DC2626"]
)
fig = aplicar_tema(fig, "Top 10 quedas (2024 - 2021)", "Diferenca (QTD_2024 - QTD_2021)", "Tipo de embarcacao")
fig.add_vline(x=0, line_width=1, line_dash="dash", line_color="#6b7280")
fig.update_traces(textposition="outside", hovertemplate="%{y}<br>Diferenca: %{x:,}<extra></extra>")

fig.write_html("../data/comparativo_quedas_2021_2024.html")
fig.show()

In [10]:
# Passo 5: Comparativo 2021 vs 2024 (Para os tipos com maior mudanca)
top_changes = (comparacao
               .assign(ABS_DIF=lambda d: d["DIF"].abs())
               .sort_values("ABS_DIF", ascending=False)
               .head(10)
               .sort_values("QTD_2024"))

fig = go.Figure()

for _, r in top_changes.iterrows():
    fig.add_trace(go.Scatter(
        x=[r["QTD_2021"], r["QTD_2024"]],
        y=[r["TIPO_EMBARCACAO"], r["TIPO_EMBARCACAO"]],
        mode="lines",
        line=dict(color="#9ca3af", width=3),
        showlegend=False,
        hoverinfo="skip"
    ))

fig.add_trace(go.Scatter(
    x=top_changes["QTD_2021"],
    y=top_changes["TIPO_EMBARCACAO"],
    mode="markers",
    marker=dict(size=10, color="#2563EB"),
    name="2021",
    hovertemplate="%{y}<br>2021: %{x:,}<extra></extra>"
))

fig.add_trace(go.Scatter(
    x=top_changes["QTD_2024"],
    y=top_changes["TIPO_EMBARCACAO"],
    mode="markers",
    marker=dict(size=10, color="#D97706"),
    name="2024",
    hovertemplate="%{y}<br>2024: %{x:,}<extra></extra>"
))

fig = aplicar_tema(fig, "Top 10 maiores mudancas - comparacao 2021 vs 2024", "Quantidade", "Tipo de embarcacao")
fig.show()

In [11]:
# Passo 5: Exportar dados de comparação e exportar o gráfico para HTML
# comparacao deve conter: TIPO_EMBARCACAO, QTD_2021, QTD_2024, DIF, VAR_%, STATUS

# CSV (recomendado para compartilhar)
comparacao.to_csv("../data/comparacao_embarcacoes_2021_2024.csv", index=False, encoding="utf-8-sig")

# Excel (.xlsx)
comparacao.to_excel("../data/comparacao_embarcacoes_2021_2024.xlsx", index=False)